mainmat: mymat.o mainmat.o
	gcc -ansi -Wall -pedamtic mymat.o mainmat.o -o mainmat
mainmat.o: mainmat.c
	gcc -ansi -Wall -pedamtic mainmat.c -o mainmat.o
maymat.o: mymat.c
	gcc -ansi -Wall -pedamtic mymat.c -o mymat.o
